# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "70d54511cff1cbd280c9c53b3fbbe481"
name = "Sahiglow Volume Bundles"
application_url = "https://sahiglow-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://sahiglow-app.onrender.com/auth/callback" ]

[app_proxy]
url = "https://sahiglow-app.onrender.com/app/proxy"
subpath = "sahiglow-proxy"
prefix = "apps"
